ARG OPENTRONS_VERSION=edge
FROM opentrons-base:${OPENTRONS_VERSION}

WORKDIR /opentrons

# Install packages from local directories
RUN python -m pip install -U ./shared-data/python
RUN python -m pip install -U ./hardware[flex]
RUN python -m pip install -U ./api
RUN python -m pip install -U pandas==1.4.3

# The default command to run when starting the container
CMD ["tail", "-f", "/dev/null"]
