services:
  opentrons-analysis:
    image: opentrons-analysis:${OPENTRONS_VERSION:-edge}
    container_name: opentrons-analysis
    volumes:
      - analysis-shared:/data
  robot-server-flex:
    image: opentrons-robot-server:${OPENTRONS_VERSION:-edge}
    build:
      context: .
      dockerfile: Dockerfile.robot-server
      args:
        OPENTRONS_VERSION: ${OPENTRONS_VERSION:-edge}
    environment:
      - PORT=31951
    env_file:
      - dev-flex.env
    ports:
      - "31951:31951"
    networks:
      - app_net
    volumes:
      - analysis-shared:/data
    container_name: robot-server-flex

  robot-server-ot2:
    image: opentrons-robot-server:${OPENTRONS_VERSION:-edge}
    build:
      context: .
      dockerfile: Dockerfile.robot-server
      args:
        OPENTRONS_VERSION: ${OPENTRONS_VERSION:-edge}
    environment:
      - PORT=31952
    env_file:
      - dev-ot2.env
    ports:
      - "31952:31952"
    networks:
      - app_net
    volumes:
      - analysis-shared:/data
    container_name: robot-server-ot2

  file-upload-app:
    build:
      context: .
      dockerfile: Dockerfile.analyze-app
    ports:
      - "5000:5000"
    networks:
      - app_net
    volumes:
      - analysis-shared:/data
    container_name: file-upload-app
    depends_on:
      - robot-server-flex
      - robot-server-ot2

networks:
  app_net:
    driver: bridge

volumes:
  analysis-shared:
